### ISSUE TITLE
Errors when testing on R7800 with XR 500 firmware

### ISSUE THREAD

**Issue by bouwew** [MatMaul/pynetgear#43]
Hi,

I was trying out the Netgear-function in Home Assistant and I am running in some trouble.
I'm using the Netgear R7800 with a modified firmware meant for the X R 5 0 0 .
When running the pynetgear script manually, this is shown:

{'NewMonthConnectionTime': datetime.timedelta(0, 60), 'NewYesterdayDownload': 0.0, 'NewTodayConnectionTime': datetime.timedelta(0, 60), 'NewLastMonthUpload': (0.0, 0.0), 'NewTodayUpload': 0.0, 'NewWeekDownload': (0.0, 0.0), 'NewMonthUpload': (0.0, 0.0), 'NewWeekConnectionTime': datetime.timedelta(0, 60), 'NewLastMonthDownload': (0.0, 0.0), 'NewYesterdayUpload': 0.0, 'NewLastMonthConnectionTime': datetime.timedelta(0, 120), 'NewMonthDownload': (0.0, 0.0), 'NewYesterdayConnectionTime': datetime.timedelta(0), 'NewTodayDownload': 0.0, 'NewWeekUpload': (0.0, 0.0)}
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 981, in emit
    msg = self.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 831, in format
    return fmt.format(record)
  File "/usr/lib/python3.5/logging/__init__.py", line 568, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.5/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not NoneType
Call stack:
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/srv/homeassistant/lib/python3.5/site-packages/pynetgear/__main__.py", line 22, in <module>
    main()
  File "/srv/homeassistant/lib/python3.5/site-packages/pynetgear/__main__.py", line 12, in main
    devices = netgear.get_attached_devices()
  File "/srv/homeassistant/lib/python3.5/site-packages/pynetgear/__init__.py", line 105, in get_attached_devices
    be: %d but is: %d""", entry_count, len(entries))
Message: 'Number of devices should                  be: %d but is: %d'
Arguments: (None, 10)
Device(signal=100, ip='192.168.1.137', name='BOUWE-PC', mac='XX', type='wired', link_rate=None, allow_or_block='Allow', device_type=None, device_model=None, ssid=None, conn_ap_mac=None)
Device(signal=100, ip='192.168.1.109', name='SOLAR-B84B', mac='XX', type='wireless', link_rate=None, allow_or_block='Allow', device_type=None, device_model=None, ssid=None, conn_ap_mac=None)
Device(signal=100, ip='192.168.1.100', name='unnamed device', mac='XX', type='wireless', link_rate=None, allow_or_block='Allow', device_type=None, device_model=None, ssid=None, conn_ap_mac=None)
Device(signal=100, ip='192.168.1.101', name='ANDROID-5728CB9FED8984F9', mac='XX', type='wireless', link_rate=5, allow_or_block='Allow', device_type=None, device_model=None, ssid=None, conn_ap_mac=None)

And several more devices are shown.

Do you have any idea why the error happens? Any fix possible?

Kind regards, bouwew

**Comment by MatMaul** [comment]
Have you tried with the just released version 0.4.1 ?
I fixed several stuffs in this part of the code, I think it is fixed.

You can do `pip install --upgrade pynetgear` in the home-assistant virtualenv if you want to test.

**Comment by bouwew** [comment]
Thanks for the suggestion I tried it, and it works!
The output is now:

{'NewLastMonthDownload': (0.0, 0.0), 'NewYesterdayUpload': 0.0, 'NewMonthConnectionTime': datetime.timedelta(0, 60), 'NewTodayConnectionTime': datetime.timedelta(0, 60), 'NewTodayUpload': 0.0, 'NewLastMonthUpload': (0.0, 0.0), 'NewWeekUpload': (0.0, 0.0), 'NewYesterdayDownload': 0.0, 'NewWeekDownload': (0.0, 0.0), 'NewYesterdayConnectionTime': datetime.timedelta(0), 'NewMonthUpload': (0.0, 0.0), 'NewLastMonthConnectionTime': datetime.timedelta(0, 120), 'NewMonthDownload': (0.0, 0.0), 'NewTodayDownload': 0.0, 'NewWeekConnectionTime': datetime.timedelta(0, 60)}
Device(signal=100, ip='192.168.1.137', name='BOUWE-PC', mac='XXX', type='wired', link_rate=None, allow_or_block='Allow', device_type=None, device_model=None, ssid=None, conn_ap_mac=None)
Device(signal=100, ip='192.168.1.109', name='SOLAR-B84B', mac='XXX', type='wireless', link_rate=None, allow_or_block='Allow', device_type=None, device_model=None, ssid=None, conn_ap_mac=None)
And so on...

**Comment by bouwew** [comment]
How do I get this update to "stick" in Home Assistant? When I restart HA there are still errors in the main HA-logging. And when I re-issue the command manually, the error is back due to pynetgear being rolled back to 0.4.0.

**Comment by MatMaul** [comment]
change the version to 0.4.1 in components/device_tracker/netgear.py or wait for next update.
